name: stylist
description: Stylist allows you to theme your Flutter application just like using CSS variables. It is really flexible and easy to use.
version: 0.0.4
author: kekland <kk.erzhan@gmail.com>
homepage: https://github.com/kekland/stylist

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: